from typing import Any, Protocol


# PostService depends on this interface, not on DummyClient specifically (easier to test/swap).
class ApiClientProtocol(Protocol):
    async def get_post(self, post_id: int) -> dict[str, Any]: ...

    async def search_posts(self, query: str) -> list[dict[str, Any]]: ...

    async def get_comments(self, post_id: int) -> list[dict[str, Any]]: ...

    async def close(self) -> None: ...
