from collections.abc import Iterable
from typing import Any, Protocol


class StorageProtocol(Protocol):
    def create(self, collection: str, key: Any, record: Any) -> None: ...

    def create_many(
        self, collection: str, pairs: Iterable[tuple[Any, Any]]
    ) -> None: ...

    def read(self, collection: str, key: Any) -> Any: ...

    def update(self, collection: str, key: Any, record: Any) -> None: ...

    def delete(self, collection: str, key: Any) -> None: ...

    def list_collection(self, collection: str) -> dict[Any, Any]: ...
